FROM node:22-alpine3.19

ENV PNPM_PATH="/pnpm"
ENV PATH="$PNPM_PATH:$PATH"
RUN corepack enable

WORKDIR /usr/src/app

COPY ./src /usr/src/app/src
COPY package.json /usr/src/app/package.json
COPY pnpm-lock.yaml /usr/src/app/pnpm-lock.yaml
COPY tsconfig.json /usr/src/app/tsconfig.json

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

USER node

CMD ["pnpm", "run", "dev"]
