services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - brain_network
  db:
    image: postgres:latest
    container_name: db
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    networks:
      - brain_network
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "250MB"
networks:
  brain_network:
    driver: bridge
