FROM node:22-alpine3.19

WORKDIR /usr/src/app

RUN npm install -g pnpm

COPY ./src /usr/src/app/src
COPY package.json /usr/src/app/package.json
COPY pnpm-lock.yaml /usr/src/app/pnpm-lock.yaml
COPY tsconfig.json /usr/src/app/tsconfig.json

RUN pnpm install 

USER node

CMD ["pnpm", "run", "dev"]
